
title: ""
description: "Portfolio cá nhân + blog CNTT (VN/EN)"
url: "" # điền https://nguyenngocchuong-cntt.github.io sau khi deploy
baseurl: ""

# Dùng remote_theme của Minimal Mistakes (được GitHub Pages hỗ trợ)
remote_theme: "mmistakes/minimal-mistakes"

locale: vi-VN

author:
  name: "Nguyễn Ngọc Chương"
  avatar: "/assets/images/avatar.jpg"
  bio: "Chuyên viên CNTT • An ninh mạng • Cloud • ERP SAP"
  location: "TP.HCM, Việt Nam"
  links:
    - label: "Email"
      url: "mailto:johnpak7849@gmail.com"
    - label: "GitHub"
      url: "https://nguyenngocchuong-cntt.github.io"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/"

# Plugins được GitHub Pages hỗ trợ
plugins:
  - jekyll-include-cache

# Navigation dùng _data/navigation.yml
collections:
  posts:
    output: true

# Defaults cho trang
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Social sharing & SEO
# minimal-mistakes có sẵn Open Graph
